name: Process MLB Games

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  mlb:
    runs-on: ubuntu-latest
    env:
      TWITTER_V1_API_KEY: ${{ secrets.TWITTER_V1_API_KEY }}
      TWITTER_V1_API_KEY_SECRET: ${{ secrets.TWITTER_V1_API_KEY_SECRET }}
      TWITTER_V1_ACCESS_TOKEN: ${{ secrets.TWITTER_V1_ACCESS_TOKEN }}
      TWITTER_V1_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_V1_ACCESS_TOKEN_SECRET }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install Python Dependencies
        working-directory: ./mlb
        run: |
          pip install -r requirements.txt
      - name: process new games
        working-directory: ./mlb
        run: python automated.py
      - name: Commit and push if changed
        run: |
          git config --global user.name 'Blake Sanie'
          git config --global user.email 'blakesanie@users.noreply.github.com'
          git add mlb/history.txt
          git commit -am "Automated update" || true
          git push || true